// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzfzXGKaV0qJmvubn0oikdFLwQcdbSpO0',
    appId: '1:832283286703:web:af9ae590fc76dca061885a',
    messagingSenderId: '832283286703',
    projectId: 'medbuddy-85345',
    authDomain: 'medbuddy-85345.firebaseapp.com',
    storageBucket: 'medbuddy-85345.firebasestorage.app',
    measurementId: 'G-D88KSNRMGX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxzDT0zPmHzzWtLfRc9GvIpuRDhowZ_yk',
    appId: '1:832283286703:android:7733639b56ae421b61885a',
    messagingSenderId: '832283286703',
    projectId: 'medbuddy-85345',
    storageBucket: 'medbuddy-85345.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDc4fI0U-dFTWMvyzcSUo3-Y-t3W0y3ImI',
    appId: '1:832283286703:ios:10a2c51179a0806061885a',
    messagingSenderId: '832283286703',
    projectId: 'medbuddy-85345',
    storageBucket: 'medbuddy-85345.firebasestorage.app',
    iosBundleId: 'com.example.medbuddyMobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDc4fI0U-dFTWMvyzcSUo3-Y-t3W0y3ImI',
    appId: '1:832283286703:ios:10a2c51179a0806061885a',
    messagingSenderId: '832283286703',
    projectId: 'medbuddy-85345',
    storageBucket: 'medbuddy-85345.firebasestorage.app',
    iosBundleId: 'com.example.medbuddyMobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzfzXGKaV0qJmvubn0oikdFLwQcdbSpO0',
    appId: '1:832283286703:web:5021ce9ba813102161885a',
    messagingSenderId: '832283286703',
    projectId: 'medbuddy-85345',
    authDomain: 'medbuddy-85345.firebaseapp.com',
    storageBucket: 'medbuddy-85345.firebasestorage.app',
    measurementId: 'G-ZQ8YVW9865',
  );
}
